### ISSUE TITLE
CRITICAL ISSUE: Credential presentation from a multisig AID is not sent to a non-issuee recipient

### ISSUE THREAD

**Issue by nkongsuwan** [provenant-dev/origin-community#13] opened 2024-11-24 14:41 UTC
**Describe the bug**
Currently, when a credential is presented from a multisig AID to a non-issuee AID, the credential will not be sent. This is becuase the recipient AID provided by the initiator and the follower are not consistent. 

Let's say a multisig AID called `aidQVI` has three members called `aidQAR1`, `aidQAR2`, and `aidQAR3`. The `aidQVI` has issued a legal entity vLEI credential to `aidLE` and wants to present the credential to `aidSally`. The `aidQAR1` initiates the credential presentation to `aidSally` by send `/multisig/exn` messages to `aidQAR2`, and `aidQAR3` for them to join and sign the presentation.

However, currently there is a bug in the joining script such that `aidQAR2`, and `aidQAR3` will present the credential to `aidLE` (which is the credential's issuee) instead of `aidSally` (which is the selected recipient). 

**To Reproduce**
1. In the `Issue` or `Hold` tab, choose a credential issued to or by a multisig AID
2. Click `Present`
3. Choose the recipient AID that is not the credential's issuee
4. Click `Submit`
5. Switch to another account which is also the member of the same multisig AID
6. Go to `Settings > Wallet Notifications`
7. Find the most recent `/multisig/exn` notification and click `View`
8. Click `Join Credential`.

Sometimes, this issue will crash the KERIA server.

**Expected behavior**

**Screenshots**
Screenshots of the initiator
<img width="927" alt="Screenshot 2567-11-24 at 21 14 54" src="https://github.com/user-attachments/assets/f665ea15-2aa3-4ee6-b713-53fecc5025a2">
<img width="931" alt="Screenshot 2567-11-24 at 21 15 11" src="https://github.com/user-attachments/assets/f16bdb85-318b-4447-a686-17af144c8ecf">

Screenshots of the follower
<img width="933" alt="Screenshot 2567-11-24 at 21 19 04" src="https://github.com/user-attachments/assets/4daa3d1b-a4ac-4dff-b9bc-36c97540fa51">
<img width="895" alt="Screenshot 2567-11-24 at 21 19 14" src="https://github.com/user-attachments/assets/478de8a9-9a52-46b3-96b1-a635fd19ec6d">

**Additional context**
I did some investigation and identified this issue in the Chrome DevTools. When `Join Credential` is clicked, the function `processExnMessage` in `WalletNotificationsTab.tsx` will be executed. 
```
const processExnMessage = async () => {
    .
    .
    .
      } else if (selectedNotification.a.r === '/multisig/exn') {
        if (exnMessage.exn.e.exn.r === '/ipex/grant')
          await joinCredentialGrant(selectedNotification)
      }
    .
    .
    .
```
This function calls another function `joinCredentialGrant` that subsequently calls `multisigGrantCredential`
```
const joinCredentialGrant = async (notification: Notification) => {
    .
    .
    .
    await multisigGrantCredential(
      signifyClient,
      groupAid.name,
      groupAid.group.localAid.name,
      grantExn.e.acdc.a.i,
      createCredentialResult
    )
    .
    .
    .
```
However, the input to this functions submits the credential to the credential's issuee `exnMessage.exn.e.exn.e.acdc.a.i` instead of the selected recipient AID, which can be found in the exchange message `exnMessage.exn.e.exn.a.i`

Here is an example of an exchange message.
```
{
  "exn": {
    "v": "KERI10JSON000adb_",
    "t": "exn",
    "d": "EDhM8ayhFls9Z3LDSOblGTk05vFti1vYo7zmeJAliNo8",
    "i": "EBXg-jppgHqKArbvI2udtnvOB3MnJzwM_g39JnKo1Aaz",
    "p": "",
    "dt": "2024-11-24T13:24:54.715000+00:00",
    "r": "/multisig/exn",
    "q": {},
    "a": {
      "gid": "EDHMHKJ-ZVDRFlTAUJawHYdilQnDh4Vc92GvOsBRfA38"
    },
    "e": {
      "exn": {
        "v": "KERI10JSON00098d_",
        "t": "exn",
        "d": "EB3zo_e4RX1Rh492m5e_7wfwsYNJrAhptl4ZM8wl1iRn",
        "i": "EDHMHKJ-ZVDRFlTAUJawHYdilQnDh4Vc92GvOsBRfA38",
        "p": "",
        "dt": "2024-11-24T13:24:51.405000+00:00",
        "r": "/ipex/grant",
        "q": {},
        "a": {
          "m": "",
          "i": "EPZN94iifUVP-3u_6BNDOFS934c8nJDU2A5bcDF9FkzT"
        },
        "e": {
          "acdc": {
            "v": "ACDC10JSON000606_",
            "d": "EC7af9a3_HuTPe61kAXNgaCXdDTQAJI8ZllsqxhcUBmG",
            "i": "EDHMHKJ-ZVDRFlTAUJawHYdilQnDh4Vc92GvOsBRfA38",
            "ri": "EEoF8EvAG09uLdxnwNe8g92yAfYj3HFrjsz0OxBLtwsi",
            "s": "EBNaNu-M9P5cgrnfl2Fvymy4E_jvxxyjb70PRtiANlJy",
            "a": {
              "d": "EFyoLoO36IMbjzUST1g-ZgmGIvtc1R1ro_piX23kbhvF",
              "i": "EFA9iSduZs9Hcncr6CYrHoRmJ1NQ5WlpT_6vRXnpeREn",
              "dt": "2024-10-16T14:12:06.041000+00:00",
              "LEI": "506700GE1G29325QX363",
              "personLegalName": "John Doe",
              "officialRole": "CEO"
            },
            "e": {
              .
              .
              .
```

**Comment by dhh1128** [comment] 2024-11-25 16:22
[from twin in jira]
This issue is being tracked in jira at https://eipi.atlassian.net/browse/DF-2577.
To send new comments there, start them with 'Tell jira:'.
The issue is assigned in jira to Cal Warshaw.
As of 2024-11-25T07:23Z, the status of the issue in jira is 'to do'.

**Comment by dhh1128** [comment] 2024-11-26 16:22
[from twin in jira]
The issue is assigned in jira to Arshdeep Singh.

**Comment by dhh1128** [comment] 2024-12-04 08:22
[from twin in jira]
As of 2024-12-03T17:40Z, the status of the issue in jira is 'doing'.

**Comment by dhh1128** [comment] 2024-12-04 20:21
[from twin in jira]
As of 2024-12-04T13:37Z, the status of the issue in jira is 'done'. Code with the fix has been deployed in production.
At 2024-12-04T13:07Z, Daniel Hardman said: fix has been tested; we’re now deploying hotfix to production
At 2024-12-04T13:08Z, Arshdeep Singh said: this issue has been fixed and tested. @Nuttawut hotfix has been deployed to Asia instance. Please test the presentation and let us know if there is any concern.

**Closed as completed by dhh1128** 2024-12-04 20:21 UTC

**Comment by dhh1128** [comment] 2026-03-16 16:37
[from twin in jira]
As of 2026-03-16T09:46Z, the status of the issue in jira is 'released'.
