### ISSUE TITLE
A new grant message should be generated when a credential is presented

### ISSUE THREAD

**Issue by nkongsuwan** [provenant-dev/origin-community#12] opened 2024-11-04 03:29 UTC
**Is your feature request related to a problem? Please describe.**
Currently, when a credential is presented, the timestamp for the grant message is taken from the credential's issuance datetime `credResult.acdc.ked?.a?.dt`. As a result, identical grant messages are generated for every presentation of the credential. This potentially makes Origin susceptible to a reply attack.

This is a function I took from the Chrome DevTools.
```
export async function multisigGrantCredential(
  client: SignifyClient,
  groupName: string,
  memberName: string,
  recipientPrefix: string,
  credResult: IssueCredentialResult
) {
  const mHab = await client.identifiers().get(memberName)
  const gHab = await client.identifiers().get(groupName)
  const members = await client.identifiers().members(groupName)

  const [grant, gsigs, end] = await client.ipex().grant({
    senderName: groupName,
    recipient: recipientPrefix,
    datetime: credResult.acdc.ked?.a?.dt,
    acdc: credResult.acdc,
    anc: credResult.anc,
    iss: credResult.iss
  })

  await client
    .ipex()
    .submitGrant(groupName, grant, gsigs, end, [recipientPrefix])

  let mstate = gHab['state']
  let sner = new CesrNumber({}, undefined, mstate['ee']['s'])
  let seal = [
    'SealEvent',
    { i: gHab['prefix'], s: sner.num, d: mstate['ee']['d'] }
  ]
  let sigers = gsigs.map((sig: any) => new signify.Siger({ qb64: sig }))
  let ims = signify.d(signify.messagize(grant, sigers, seal))
  let atc = ims.substring(grant.size)
  atc += end
  let gembeds = {
    exn: [grant, atc]
  }

  const recipients = members.signing
    .map((m: { aid: string }) => m.aid)
    .filter((aid: string) => aid !== mHab.prefix)

  if (recipients.length > 0) {
    consoleLog(
      `Sending join grant credential exn message to other members : `,
      recipients
    )

    await client
      .exchanges()
      .send(
        mHab.name,
        'multisig',
        mHab,
        '/multisig/exn',
        { gid: gHab['prefix'] },
        gembeds,
        recipients
      )
  }
}
```

**Describe the solution you'd like**
When a credential is presented, a current datetime should be used when the "Present" button is clicked. This datetime must also be propagated to and used by other multisig members (if any) in the notification.

**Comment by dhh1128** [comment] 2024-11-04 16:21
[from twin in jira]
This issue is being tracked in jira at https://eipi.atlassian.net/browse/DF-2565.
To send new comments there, start them with 'Tell jira:'.
The issue is assigned in jira to Cal Warshaw.
As of 2024-11-04T07:23Z, the status of the issue in jira is 'to do'.

**Comment by dhh1128** [comment] 2024-12-04 16:22
[from twin in jira]
As of 2024-12-04T08:44Z, the status of the issue in jira is 'doing'.

**Comment by dhh1128** [comment] 2024-12-04 20:21
[from twin in jira]
The issue is assigned in jira to Arshdeep Singh.
As of 2024-12-04T13:31Z, the status of the issue in jira is 'done'. Code with the fix has been deployed in production.
At 2024-12-04T13:09Z, Arshdeep Singh said: this issue has been fixed and tested. @Nuttawut fix has been deployed to Asia instance. Please test and let us know if there is any concern.

**Closed as completed by dhh1128** 2024-12-04 20:21 UTC

**Comment by dhh1128** [comment] 2026-03-16 16:37
[from twin in jira]
As of 2026-03-16T09:46Z, the status of the issue in jira is 'released'.
