### ISSUE TITLE
Cannot click multisig group participants when there are too many resolved identifiers in "Connections"

### ISSUE THREAD

**Issue by nkongsuwan** [provenant-dev/origin-community#5] opened 2024-08-16 15:09 UTC
**Describe the bug**
When a wallet has resolved a lot of identifiers, the bottom part of the drop-down list of "Other Participants Identifiers" will be hidden behind the popup window "Create multisig identifier".

Note: the hidden identifiers can still be chosen using a keyboard. 

**To Reproduce**
1. Resolve a lot of identifiers
2. Try to create a multisig group and choose the participant identifier at the bottom of the drop-down list.

**Expected behavior**
The drop-down list should be hidden behind the popup window.

**Screenshots**
![Screenshot 2567-08-16 at 20 17 12](https://github.com/user-attachments/assets/ef975d0d-0c48-40a7-b2ea-02bc0f0c04fa)

**Comment by dhh1128** [comment] 2024-08-21 21:33
[from twin in jira]
This issue tracks jira  https://eipi.atlassian.net/browse/DF-2314.
To send new comments there, start them with 'Tell jira:'.
As of 2024-08-21T17:10Z, the status of the issue in jira is 'to do'.

**Comment by dhh1128** [comment] 2024-08-21 22:39
[from twin in jira]
The issue is assigned in jira to Md. Fahad-Uz-Zaman Khan.

**Comment by dhh1128** [comment] 2024-08-21 23:12
[from twin in jira]
At 2024-08-21T19:08Z, Daniel Hardman said: assigned to the current sprint

**Comment by dhh1128** [comment] 2024-08-22 12:22
[from twin in jira]
As of 2024-08-22T07:59Z, the status of the issue in jira is 'doing'.

**Comment by dhh1128** [comment] 2024-08-22 16:22
[from twin in jira]
At 2024-08-22T11:24Z, Daniel Hardman said: Perfect fix, Fahad. Thank you! @Nuttawut: we will be deploying this fix soon.

**Comment by dhh1128** [comment] 2024-08-23 09:53
[from twin in jira]
As of 2024-08-23T05:48Z, the status of the issue in jira is 'in review'.

**Comment by dhh1128** [comment] 2024-08-28 12:22
[from twin in jira]
As of 2024-08-28T08:18Z, the status of the issue in jira is 'in dev'.

**Comment by dhh1128** [comment] 2024-08-28 17:47
[from twin in jira]
As of 2024-08-28T10:56Z, the status of the issue in jira is 'in stage (qa)'.

**Comment by dhh1128** [comment] 2024-09-17 16:21
[from twin in jira]
As of 2024-09-17T08:58Z, the status of the issue in jira is 'done'. Code with the fix has been deployed in production.

**Closed as completed by dhh1128** 2024-09-17 16:21 UTC
